# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hoop < Formula
  desc "Hoop allows acessing any infra-structure resource easily and secure."
  homepage "https://github.com/hoophq/hoopcli"
  version "1.15.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/1.15.23/hoop_1.15.23_Darwin_amd64.tar.gz"
      sha256 "14769479c56b99dfdd5a42272e84587dd3e356e177e4631e29758172ea5fc6da"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.hoop.dev/release/1.15.23/hoop_1.15.23_Darwin_arm64.tar.gz"
      sha256 "7f9cb243b7b149f4638d25270c9040fe0425b21af8c0e0cbbe00e00462137381"

      def install
        bin.install "hoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.hoop.dev/release/1.15.23/hoop_1.15.23_Linux_arm64.tar.gz"
      sha256 "6ae7c4119f816b11f6d72f17ba9354ef169f2d0ff6102c7f47032d42c31b14f8"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/1.15.23/hoop_1.15.23_Linux_amd64.tar.gz"
      sha256 "7bc55df2c675bc2734b63c3fb0d76bda1d257c016c4be01ab2cf5130a34d8da5"

      def install
        bin.install "hoop"
      end
    end
  end
end
