# typed: false
# frozen_string_literal: true

# This file is autogenerated. DO NOT EDIT.
class Hoop < Formula
  desc "Hoop allows acessing any infra-structure resource easily and secure."
  homepage "https://github.com/hoophq/hoopcli"
  version "1.19.41"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/1.19.41/hoop_1.19.41_Darwin_amd64.tar.gz"
      sha256 "cae74cc48a6d5efba185df4bd5fb5be2ad9217dce072b417f58b0c9869f48409"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.hoop.dev/release/1.19.41/hoop_1.19.41_Darwin_arm64.tar.gz"
      sha256 "f947a39fff230f3e78328d7a174b735a54c8f00b68b77484d77e3c63b0832662"

      def install
        bin.install "hoop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.hoop.dev/release/1.19.41/hoop_1.19.41_Linux_arm64.tar.gz"
      sha256 "99c37e91c64ca5665c4768c8ea20f33b57c5933e3a65df1c2d5c4a11d8325de7"

      def install
        bin.install "hoop"
      end
    end
    if Hardware::CPU.intel?
      url "https://releases.hoop.dev/release/1.19.41/hoop_1.19.41_Linux_amd64.tar.gz"
      sha256 "9f24075472032d7bf0c2c4594463c73b457850a84a0f039fbad0d21dc1bb292b"

      def install
        bin.install "hoop"
      end
    end
  end
end
